apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: robokart
spec:
  selector:
    app: payment
    project: robokart
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port