apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: robokart
  labels:
    app: rabbitmq
    project: robokart
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 5672 #service-port
    targetPort: 5672
  clusterIP: None
  selector:
    app: rabbitmq
    project: robokart
    tier: db