apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: robokart
  labels:
    app: redis
    project: robokart
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 6379 #service-port
    targetPort: 6379
  clusterIP: None
  selector:
    app: redis
    project: robokart
    tier: db