apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: robokart
  labels:
    app: redis
    project: robokart
    tier: db
spec:
  selector:
    matchLabels:
      app: redis
      project: robokart
      tier: db
  serviceName: "redis"
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        app: redis
        project: robokart
        tier: db
    spec:
      containers:
      - name: redis
        image: redis
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi